const locations = [
  "Asa Sul",
  "Asa Norte",
  "Samambaia",
  "Ceilândia",
  "Taguatinga",
  "Águas Claras",
  "Lago Sul",
  "Lago Norte",
  "Gama",
  "Planaltina",
  "Sobradinho",
  "Brazlândia",
  "Santa Maria",
  "Paranoá",
  "Recanto das Emas",
  "Guará",
  "Sudoeste/Octogonal",
  "Cruzeiro",
  "Park Way",
  "Candangolândia",
  "Riacho Fundo",
  "Riacho Fundo II",
  "SCIA (Estrutural)",
  "Vicente Pires",
  "Núcleo Bandeirante",
  "Águas Lindas - GO",
  "Santo Antônio do Descoberto - GO",
  "Planaltina de Goiás - GO",
  "Formosa - GO",
  "Luziânia - GO",
  "Valparaíso de Goiás - GO",
  "Novo Gama - GO",
];

export default locations;
